# Generated by Django 4.2.9 on 2024-02-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_name_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
