# Generated by Django 4.2.9 on 2024-02-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_product_name_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyNow',
        ),
    ]
