# Generated by Django 4.2.9 on 2024-02-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_user_id_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
