# Generated by Django 4.2.9 on 2024-02-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='BuyNow',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
