# Generated by Django 4.2.9 on 2024-02-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_cartitem_buynow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
